services:
    nginx:
        image: 'nginx:stable-alpine'
        ports:
            - '127.0.0.1:8000:80'
        volumes:
            - './api:/var/www/html'
            - './infra/nginx/default.conf:/etc/nginx/conf.d/default.conf'
        depends_on:
            - 'php'
        networks:
            - 'backend'

    php:
        build:
            context: 'infra/php'
            dockerfile: 'Dockerfile'
            args:
                USER_ID: '$USER_ID'
                GROUP_ID: '$GROUP_ID'
        volumes:
            - './api:/var/www/html'
        working_dir: '/var/www/html'
        depends_on:
            - 'redis'
        networks:
            - 'backend'
        user: 'www-data'

    db:
        image: 'mariadb:11.7'
        environment:
            MARIADB_USER: 'elsan'
            MARIADB_PASSWORD: 'elsan'
            MARIADB_ROOT_PASSWORD: 'elsan'
            MARIADB_DATABASE: 'elsan'
        ports:
            - '127.0.0.1:3306:3306'
        networks:
            - 'backend'

    redis:
        image: 'redis:alpine'
        networks:
            - 'backend'

    mailhog:
        image: 'mailhog/mailhog:latest'
        networks:
            - 'backend'

    node:
        build:
            context: 'infra/node'
            dockerfile: 'Dockerfile'
            args:
                USER_ID: '$USER_ID'
                GROUP_ID: '$GROUP_ID'
        working_dir: '/var/www/html'
        volumes:
            - './front:/var/www/html'
        command: 'sh -c "npm install && npm run dev"'
        ports:
            - '127.0.0.1:5173:5173'
        user: 'node'

networks:
    backend:
        driver: 'bridge'
